INSERT INTO sys_countries(name) values('BRASIL');
INSERT INTO sys_countries(name) values('AFEGANISTAO');
INSERT INTO sys_countries(name) values('AFRICA DO SUL');
INSERT INTO sys_countries(name) values('REPUBLICA DA ALBANIA');
INSERT INTO sys_countries(name) values('ALEMANHA');
INSERT INTO sys_countries(name) values('ANDORRA');
INSERT INTO sys_countries(name) values('ANGOLA');
INSERT INTO sys_countries(name) values('ANGUILLA');
INSERT INTO sys_countries(name) values('ANTIGUA E BARBUDA');
INSERT INTO sys_countries(name) values('ANTILHAS HOLANDESAS');
INSERT INTO sys_countries(name) values('ARABIA SAUDITA');
INSERT INTO sys_countries(name) values('ARGELIA');
INSERT INTO sys_countries(name) values('ARGENTINA');
INSERT INTO sys_countries(name) values('REPUBLICA DA ARMENIA');
INSERT INTO sys_countries(name) values('ARUBA');
INSERT INTO sys_countries(name) values('AUSTRALIA');
INSERT INTO sys_countries(name) values('AUSTRIA');
INSERT INTO sys_countries(name) values('REPUBLICA DO AZERBAIJAO');
INSERT INTO sys_countries(name) values('ILHAS BAHAMAS');
INSERT INTO sys_countries(name) values('ILHAS BAHREIN');
INSERT INTO sys_countries(name) values('BANGLADESH');
INSERT INTO sys_countries(name) values('BARBADOS');
INSERT INTO sys_countries(name) values('REPUBLICA DA BELARUS');
INSERT INTO sys_countries(name) values('BELGICA');
INSERT INTO sys_countries(name) values('BELIZE');
INSERT INTO sys_countries(name) values('BENIN');
INSERT INTO sys_countries(name) values('BERMUDAS');
INSERT INTO sys_countries(name) values('BOLIVIA');
INSERT INTO sys_countries(name) values('REPUBLICA DA BOSNIA-HERZEGOVINA');
INSERT INTO sys_countries(name) values('BOTSUANA');
INSERT INTO sys_countries(name) values('BRUNEI');
INSERT INTO sys_countries(name) values('REPUBLICA DA BULGARIA');
INSERT INTO sys_countries(name) values('BURKINA FASO');
INSERT INTO sys_countries(name) values('BURUNDI');
INSERT INTO sys_countries(name) values('BUTAO');
INSERT INTO sys_countries(name) values('REPUBLICA DE CABO VERDE');
INSERT INTO sys_countries(name) values('CAMAROES');
INSERT INTO sys_countries(name) values('CAMBOJA');
INSERT INTO sys_countries(name) values('CANADA');
INSERT INTO sys_countries(name) values('ILHAS CANARIAS');
INSERT INTO sys_countries(name) values('CATAR');
INSERT INTO sys_countries(name) values('ILHAS CAYMAN');
INSERT INTO sys_countries(name) values('REPUBLICA DO CAZAQUISTAO');
INSERT INTO sys_countries(name) values('CHADE');
INSERT INTO sys_countries(name) values('CHILE');
INSERT INTO sys_countries(name) values('REPUBLICA POPULAR CHINA');
INSERT INTO sys_countries(name) values('CHIPRE');
INSERT INTO sys_countries(name) values('ILHAS CHRISTMAS (NAVIDAD)');
INSERT INTO sys_countries(name) values('CINGAPURA');
INSERT INTO sys_countries(name) values('ILHAS COCOS-KEELING');
INSERT INTO sys_countries(name) values('COLOMBIA');
INSERT INTO sys_countries(name) values('ILHAS COMORES');
INSERT INTO sys_countries(name) values('CONGO');
INSERT INTO sys_countries(name) values('REPUBLICA DEMOCRATICA DO CONGO');
INSERT INTO sys_countries(name) values('ILHAS COOK');
INSERT INTO sys_countries(name) values('REP.POP.DEMOCRATICA COREIA');
INSERT INTO sys_countries(name) values('REPUBLICA DA COREIA');
INSERT INTO sys_countries(name) values('COSTA DO MARFIM');
INSERT INTO sys_countries(name) values('COSTA RICA');
INSERT INTO sys_countries(name) values('COVEITE');
INSERT INTO sys_countries(name) values('REPUBLICA DA CROACIA');
INSERT INTO sys_countries(name) values('CUBA');
INSERT INTO sys_countries(name) values('DELEGACAO ESPECIAL DA PALESTINA');
INSERT INTO sys_countries(name) values('DINAMARCA');
INSERT INTO sys_countries(name) values('DJIBUTI');
INSERT INTO sys_countries(name) values('ILHA DOMINICA');
INSERT INTO sys_countries(name) values('EGITO');
INSERT INTO sys_countries(name) values('EL SALVADOR');
INSERT INTO sys_countries(name) values('EMIRADOS ARABES UNIDOS');
INSERT INTO sys_countries(name) values('EQUADOR');
INSERT INTO sys_countries(name) values('ERITREIA');
INSERT INTO sys_countries(name) values('REPUBLICA ESLOVACA');
INSERT INTO sys_countries(name) values('REPUBLICA DA ESLOVENIA');
INSERT INTO sys_countries(name) values('ESPANHA');
INSERT INTO sys_countries(name) values('ESTADOS UNIDOS');
INSERT INTO sys_countries(name) values('REPUBLICA DA ESTONIA');
INSERT INTO sys_countries(name) values('ETIOPIA');
INSERT INTO sys_countries(name) values('FALKLAND (ILHAS MALVINAS)');
INSERT INTO sys_countries(name) values('ILHAS FEROE');
INSERT INTO sys_countries(name) values('FIJI');
INSERT INTO sys_countries(name) values('FILIPINAS');
INSERT INTO sys_countries(name) values('FINLANDIA');
INSERT INTO sys_countries(name) values('FORMOSA (TAIWAN)');
INSERT INTO sys_countries(name) values('FRANCA');
INSERT INTO sys_countries(name) values('GABAO');
INSERT INTO sys_countries(name) values('GAMBIA');
INSERT INTO sys_countries(name) values('GANA');
INSERT INTO sys_countries(name) values('REPUBLICA DA GEORGIA');
INSERT INTO sys_countries(name) values('GIBRALTAR');
INSERT INTO sys_countries(name) values('GRANADA');
INSERT INTO sys_countries(name) values('GRECIA');
INSERT INTO sys_countries(name) values('GROENLANDIA');
INSERT INTO sys_countries(name) values('GUADALUPE');
INSERT INTO sys_countries(name) values('GUAM');
INSERT INTO sys_countries(name) values('GUATEMALA');
INSERT INTO sys_countries(name) values('GUIANA');
INSERT INTO sys_countries(name) values('GUIANA FRANCESA');
INSERT INTO sys_countries(name) values('GUINE');
INSERT INTO sys_countries(name) values('GUINE-BISSAU');
INSERT INTO sys_countries(name) values('GUINE-EQUATORIAL');
INSERT INTO sys_countries(name) values('HAITI');
INSERT INTO sys_countries(name) values('HONDURAS');
INSERT INTO sys_countries(name) values('HONG KONG');
INSERT INTO sys_countries(name) values('REPUBLICA DA HUNGRIA');
INSERT INTO sys_countries(name) values('IEMEN');
INSERT INTO sys_countries(name) values('INDIA');
INSERT INTO sys_countries(name) values('INDONESIA');
INSERT INTO sys_countries(name) values('REPUBLICA ISLAMICA DO IRA');
INSERT INTO sys_countries(name) values('IRAQUE');
INSERT INTO sys_countries(name) values('IRLANDA');
INSERT INTO sys_countries(name) values('ISLANDIA');
INSERT INTO sys_countries(name) values('ISRAEL');
INSERT INTO sys_countries(name) values('ITALIA');
INSERT INTO sys_countries(name) values('JAMAICA');
INSERT INTO sys_countries(name) values('JAPAO');
INSERT INTO sys_countries(name) values('ILHA DO CANAL JERSEY');
INSERT INTO sys_countries(name) values('ILHAS JOHNSTON');
INSERT INTO sys_countries(name) values('JORDANIA');
INSERT INTO sys_countries(name) values('KIRIBATI');
INSERT INTO sys_countries(name) values('REP.POP.DEMOCR.DO LAOS');
INSERT INTO sys_countries(name) values('ILHAS LEBUAN');
INSERT INTO sys_countries(name) values('LESOTO');
INSERT INTO sys_countries(name) values('REPUBLICA DA LETONIA');
INSERT INTO sys_countries(name) values('LIBANO');
INSERT INTO sys_countries(name) values('LIBERIA');
INSERT INTO sys_countries(name) values('LIBIA');
INSERT INTO sys_countries(name) values('LIECHTENSTEIN');
INSERT INTO sys_countries(name) values('REPUBLICA DA LITUANIA');
INSERT INTO sys_countries(name) values('LUXEMBURGO');
INSERT INTO sys_countries(name) values('MACAU');
INSERT INTO sys_countries(name) values('ANT.REP.IUGOSLAVA MACEDONIA');
INSERT INTO sys_countries(name) values('MADAGASCAR');
INSERT INTO sys_countries(name) values('ILHA DA MADEIRA');
INSERT INTO sys_countries(name) values('MALASIA');
INSERT INTO sys_countries(name) values('MALAVI');
INSERT INTO sys_countries(name) values('MALDIVAS');
INSERT INTO sys_countries(name) values('MALI');
INSERT INTO sys_countries(name) values('MALTA');
INSERT INTO sys_countries(name) values('ILHA DE MAN');
INSERT INTO sys_countries(name) values('MARIANAS DO NORTE');
INSERT INTO sys_countries(name) values('MARROCOS');
INSERT INTO sys_countries(name) values('ILHAS MARSHALL');
INSERT INTO sys_countries(name) values('MARTINICA');
INSERT INTO sys_countries(name) values('MAURICIO');
INSERT INTO sys_countries(name) values('MAURITANIA');
INSERT INTO sys_countries(name) values('MEXICO');
INSERT INTO sys_countries(name) values('MIANMAR (BIRMANIA)');
INSERT INTO sys_countries(name) values('MICRONESIA');
INSERT INTO sys_countries(name) values('ILHAS MIDWAY');
INSERT INTO sys_countries(name) values('MOCAMBIQUE');
INSERT INTO sys_countries(name) values('REPUBLICA DA MOLDAVIA');
INSERT INTO sys_countries(name) values('MONACO');
INSERT INTO sys_countries(name) values('MONGOLIA');
INSERT INTO sys_countries(name) values('MONTENEGRO');
INSERT INTO sys_countries(name) values('ILHAS MONTSERRAT');
INSERT INTO sys_countries(name) values('NAMIBIA');
INSERT INTO sys_countries(name) values('NAURU');
INSERT INTO sys_countries(name) values('NEPAL');
INSERT INTO sys_countries(name) values('NICARAGUA');
INSERT INTO sys_countries(name) values('NIGER');
INSERT INTO sys_countries(name) values('NIGERIA');
INSERT INTO sys_countries(name) values('ILHA NIUE');
INSERT INTO sys_countries(name) values('ILHA NORFOLK');
INSERT INTO sys_countries(name) values('NORUEGA');
INSERT INTO sys_countries(name) values('NOVA CALEDONIA');
INSERT INTO sys_countries(name) values('NOVA ZELANDIA');
INSERT INTO sys_countries(name) values('OMA');
INSERT INTO sys_countries(name) values('ILHAS DO PACIFICO');
INSERT INTO sys_countries(name) values('PAISES BAIXOS (HOLANDA)');
INSERT INTO sys_countries(name) values('PALAU');
INSERT INTO sys_countries(name) values('PANAMA');
INSERT INTO sys_countries(name) values('PAPUA NOVA GUINE');
INSERT INTO sys_countries(name) values('PAQUISTAO');
INSERT INTO sys_countries(name) values('PARAGUAI');
INSERT INTO sys_countries(name) values('PERU');
INSERT INTO sys_countries(name) values('ILHA DE PITCAIRN');
INSERT INTO sys_countries(name) values('POLINESIA FRANCESA');
INSERT INTO sys_countries(name) values('REPUBLICA DA POLONIA');
INSERT INTO sys_countries(name) values('PORTO RICO');
INSERT INTO sys_countries(name) values('PORTUGAL');
INSERT INTO sys_countries(name) values('QUENIA');
INSERT INTO sys_countries(name) values('REPUBLICA DA QUIRGUIZ');
INSERT INTO sys_countries(name) values('REINO UNIDO');
INSERT INTO sys_countries(name) values('REPUBLICA CENTRO-AFRICANA');
INSERT INTO sys_countries(name) values('REPUBLICA DOMINICANA');
INSERT INTO sys_countries(name) values('REUNIAO, ILHA');
INSERT INTO sys_countries(name) values('ROMENIA');
INSERT INTO sys_countries(name) values('RUANDA');
INSERT INTO sys_countries(name) values('FEDERACAO DA RUSSIA');
INSERT INTO sys_countries(name) values('SAARA OCIDENTAL');
INSERT INTO sys_countries(name) values('ILHAS SALOMAO');
INSERT INTO sys_countries(name) values('SAMOA');
INSERT INTO sys_countries(name) values('SAMOA AMERICANA');
INSERT INTO sys_countries(name) values('SAN MARINO');
INSERT INTO sys_countries(name) values('SANTA HELENA');
INSERT INTO sys_countries(name) values('SANTA LUCIA');
INSERT INTO sys_countries(name) values('SAINT KITTS E NEVIS');
INSERT INTO sys_countries(name) values('ILHAS SAO CRISTOVAO E NEVES');
INSERT INTO sys_countries(name) values('SAO PEDRO E MIQUELON');
INSERT INTO sys_countries(name) values('ILHAS SAO TOME E PRINCIPE');
INSERT INTO sys_countries(name) values('SAO VICENTE E GRANADINAS');
INSERT INTO sys_countries(name) values('SENEGAL');
INSERT INTO sys_countries(name) values('SERRA LEOA');
INSERT INTO sys_countries(name) values('SERVIA');
INSERT INTO sys_countries(name) values('SEYCHELLES');
INSERT INTO sys_countries(name) values('REPUBLICA ARABE DA SIRIA');
INSERT INTO sys_countries(name) values('SOMALIA');
INSERT INTO sys_countries(name) values('SRI LANKA');
INSERT INTO sys_countries(name) values('SUAZILANDIA');
INSERT INTO sys_countries(name) values('SUDAO');
INSERT INTO sys_countries(name) values('SUECIA');
INSERT INTO sys_countries(name) values('SUICA');
INSERT INTO sys_countries(name) values('SURINAME');
INSERT INTO sys_countries(name) values('REPUBLICA DO TADJIQUISTAO');
INSERT INTO sys_countries(name) values('TAILANDIA');
INSERT INTO sys_countries(name) values('REP. UNIDA DA TANZANIA');
INSERT INTO sys_countries(name) values('REPUBLICA TCHECA');
INSERT INTO sys_countries(name) values('TERRITORIO BRITANICO NO OCEANO INDICO');
INSERT INTO sys_countries(name) values('TIMOR LESTE');
INSERT INTO sys_countries(name) values('TOGO');
INSERT INTO sys_countries(name) values('TONGA');
INSERT INTO sys_countries(name) values('ILHAS TOQUELAU');
INSERT INTO sys_countries(name) values('TRINIDAD E TOBAGO');
INSERT INTO sys_countries(name) values('TUNISIA');
INSERT INTO sys_countries(name) values('ILHAS TURCAS E CAICOS');
INSERT INTO sys_countries(name) values('REPUBLICA DO TURCOMENISTAO');
INSERT INTO sys_countries(name) values('TURQUIA');
INSERT INTO sys_countries(name) values('TUVALU');
INSERT INTO sys_countries(name) values('UCRANIA');
INSERT INTO sys_countries(name) values('UGANDA');
INSERT INTO sys_countries(name) values('URUGUAI');
INSERT INTO sys_countries(name) values('REPUBLICA DO UZBEQUISTAO');
INSERT INTO sys_countries(name) values('VANUATU');
INSERT INTO sys_countries(name) values('EST. DA CIDADE DO VATICANO');
INSERT INTO sys_countries(name) values('VENEZUELA');
INSERT INTO sys_countries(name) values('VIETNA');
INSERT INTO sys_countries(name) values('ILHAS (BRITANICAS) VIRGENS');
INSERT INTO sys_countries(name) values('ILHAS (E.U.A.) VIRGENS');
INSERT INTO sys_countries(name) values('ILHA WAKE');
INSERT INTO sys_countries(name) values('ILHAS WALLIS E FUTUNA');
INSERT INTO sys_countries(name) values('ZAMBIA');
INSERT INTO sys_countries(name) values('ZIMBABUE');
INSERT INTO sys_countries(name) values('CURAÇAO');
INSERT INTO sys_countries(name) values('ILHA DO CANAL GUERNSEY');
